title: "HIZHOON"
email: know0510@gmail.com
timezone: UTC
baseurl: "hizhoon.github.io"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Hizhoon
paginate: 30
disqus: 'zh'
locale: ko_KR
lang: ko_KR
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  hizhoon:
    name: Hizhoon
    display_name: Hizhoon
    avatar: 'assets/images/sal.png'
    email: know0510@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: null
    description: "Hi, my name is jihoon."
  
# Social
social:
  instagram: null
  facebook: null
  twitter: null

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
